language: python
python:
- '3.6'
- '3.7'
install:
- pip install --upgrade pytest pytest-cov codecov numpy>=1.16
- python setup.py install

script:
- luigid --background
- python -m pytest -vv --cov=morgoth/
- codecov --token=92cb7f46-16e6-4a3d-beb6-9e2da9684d07
