language: python
python:
- '3.6'
- '3.7'

compiler:
  - gcc

env:
  NUMBA_DISABLE_JIT=1 MULTINEST_TAG=v3.10 WITHMPI=no MORGOTH_BASE_URL=http://grb.mpe.mpg.de MORGOTH_AUTH_TOKEN=1234
  
before_install:
  - sudo apt-get install -qq libblas{3,-dev} liblapack{3,-dev} libatlas{3-base,-dev} cmake build-essential git gfortran
    # Install and test
  - git clone --branch ${MULTINEST_TAG} https://github.com/JohannesBuchner/MultiNest
  - mkdir -p MultiNest/build; pushd MultiNest/build; cmake .. && make && popd
  - export LD_LIBRARY_PATH=MultiNest/lib/:${LD_LIBRARY_PATH} 
  

install:
- pip install --upgrade pytest pytest-cov codecov numpy>=1.16 cython
- pip install git+https://github.com/grburgess/gbm_drm_gen
- pip install git+https://github.com/threeML/threeML.git@jmb_py2to3
- python setup.py install

script:
- luigid --background --logdir . --state-path . 
- python -m pytest -vv --cov=morgoth/
- codecov --token=92cb7f46-16e6-4a3d-beb6-9e2da9684d07
