language: python
python:
- '3.6'
- '3.7'
env:
  NUMBA_DISABLE_JIT=1
before_install:
  - sudo apt-get install gfortran
install:
- pip install --upgrade pytest pytest-cov codecov numpy>=1.16 cython
- pip install git+https://github.com/grburgess/gbm_drm_gen
- pip install git+https://github.com/threeML/threeML.git/jmb_py2to3
- python setup.py install

script:
- luigid --background --logdir . --state-path . 
- python -m pytest -vv --cov=morgoth/
- codecov --token=92cb7f46-16e6-4a3d-beb6-9e2da9684d07
